package com.aisupercleaner.ultimate.presentation.theme

import androidx.compose.ui.graphics.Color

val OceanBlue_PrimaryLight = Color(0xFF1565C0)
val OceanBlue_OnPrimaryLight = Color(0xFFFFFFFF)
val OceanBlue_PrimaryContainerLight = Color(0xFFD4E4FF)
val OceanBlue_OnPrimaryContainerLight = Color(0xFF001C39)
val OceanBlue_PrimaryDark = Color(0xFFA2C9FF)
val OceanBlue_OnPrimaryDark = Color(0xFF00315E)
val OceanBlue_PrimaryContainerDark = Color(0xFF004883)
val OceanBlue_OnPrimaryContainerDark = Color(0xFFD4E4FF)

val RoyalPurple_PrimaryLight = Color(0xFF6A4CBA)
val RoyalPurple_PrimaryDark = Color(0xFFCFBCFF)
val RoyalPurple_ContainerLight = Color(0xFFEADDFF)
val RoyalPurple_OnContainerLight = Color(0xFF22005D)
val RoyalPurple_ContainerDark = Color(0xFF4F378A)
val RoyalPurple_OnContainerDark = Color(0xFFEADDFF)

val EmeraldGreen_PrimaryLight = Color(0xFF006A60)
val EmeraldGreen_PrimaryDark = Color(0xFF4FDBCD)
val EmeraldGreen_ContainerLight = Color(0xFFB2F1E6)
val EmeraldGreen_OnContainerLight = Color(0xFF00201C)
val EmeraldGreen_ContainerDark = Color(0xFF005048)
val EmeraldGreen_OnContainerDark = Color(0xFFB2F1E6)

val SunsetOrange_PrimaryLight = Color(0xFFB8500A)
val SunsetOrange_PrimaryDark = Color(0xFFFFB68D)
val SunsetOrange_ContainerLight = Color(0xFFFFDCC7)
val SunsetOrange_OnContainerLight = Color(0xFF351000)
val SunsetOrange_ContainerDark = Color(0xFF8D3200)
val SunsetOrange_OnContainerDark = Color(0xFFFFDCC7)

val CrimsonRed_PrimaryLight = Color(0xFFB3261E)
val CrimsonRed_PrimaryDark = Color(0xFFFFB4AB)
val CrimsonRed_ContainerLight = Color(0xFFFFDAD6)
val CrimsonRed_OnContainerLight = Color(0xFF410002)
val CrimsonRed_ContainerDark = Color(0xFF93000A)
val CrimsonRed_OnContainerDark = Color(0xFFFFDAD6)

val TurquoiseTeal_PrimaryLight = Color(0xFF006780)
val TurquoiseTeal_PrimaryDark = Color(0xFF56D5F5)
val TurquoiseTeal_ContainerLight = Color(0xFFB8EAFF)
val TurquoiseTeal_OnContainerLight = Color(0xFF001F29)
val TurquoiseTeal_ContainerDark = Color(0xFF004D62)
val TurquoiseTeal_OnContainerDark = Color(0xFFB8EAFF)

val RosePink_PrimaryLight = Color(0xFF984061)
val RosePink_PrimaryDark = Color(0xFFFFB0C9)
val RosePink_ContainerLight = Color(0xFFFFD9E3)
val RosePink_OnContainerLight = Color(0xFF3E001D)
val RosePink_ContainerDark = Color(0xFF7B2949)
val RosePink_OnContainerDark = Color(0xFFFFD9E3)

val MidnightIndigo_PrimaryLight = Color(0xFF3F51B5)
val MidnightIndigo_PrimaryDark = Color(0xFFBEC6FF)
val MidnightIndigo_ContainerLight = Color(0xFFE0E0FF)
val MidnightIndigo_OnContainerLight = Color(0xFF00105C)
val MidnightIndigo_ContainerDark = Color(0xFF293CA0)
val MidnightIndigo_OnContainerDark = Color(0xFFE0E0FF)

val Neutral_LightBackground = Color(0xFFFDFBFF)
val Neutral_LightSurface = Color(0xFFFDFBFF)
val Neutral_LightSurfaceVariant = Color(0xFFE1E2EC)
val Neutral_LightOnSurface = Color(0xFF1A1B20)
val Neutral_LightOnSurfaceVariant = Color(0xFF44464F)
val Neutral_LightOutline = Color(0xFF757780)

val Neutral_DarkBackground = Color(0xFF121318)
val Neutral_DarkSurface = Color(0xFF121318)
val Neutral_DarkSurfaceVariant = Color(0xFF44464F)
val Neutral_DarkOnSurface = Color(0xFFE3E1E9)
val Neutral_DarkOnSurfaceVariant = Color(0xFFC5C6D0)
val Neutral_DarkOutline = Color(0xFF8F9099)

val SuccessLight = Color(0xFF2E7D32)
val SuccessDark = Color(0xFF81C784)
val WarningLight = Color(0xFFE65100)
val WarningDark = Color(0xFFFFB74D)
val ErrorLight = Color(0xFFC62828)
val ErrorDark = Color(0xFFEF9A9A)
val InfoLight = Color(0xFF0277BD)
val InfoDark = Color(0xFF4FC3F7)
